version: "3.9"

services:
  # trino:
  #   hostname: trino
  #   image: 'trinodb/trino:422'
  #   ports:
  #     - '9080:9080'
  #   volumes:
  #     - ./trino/coordinator/etc:/etc/trino:ro

  # customersdb:
  #   image: postgres:15
  #   volumes:
  #     - ./customersdb/init-customers.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./customersdb/raw_customers.csv:/home/dump/raw_customers.csv
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "15432:5432"

  # ordersdb:
  #   image: postgres:15
  #   volumes:
  #     - ./ordersdb/init-orders.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./ordersdb/raw_orders.csv:/home/dump/raw_orders.csv
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "25432:5432"

  # paymentsdb:
  #   image: postgres:15
  #   volumes:
  #     - ./paymentsdb/init-payments.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./paymentsdb/raw_payments.csv:/home/dump/raw_payments.csv
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "35432:5432"

  dbt-pipeline:
    container_name: "${COMPOSE_PROJECT_NAME}"
    build:
      context: ./dbt_pipeline
    image: "desisivio/${COMPOSE_PROJECT_NAME}_dev"
